
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action newAction;
	
	private global::Gtk.Action FileMenu;
	
	private global::Gtk.Action newAction1;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action saveAsAction;
	
	private global::Gtk.Action CompileMenu;
	
	private global::Gtk.Action compileAction;
	
	private global::Gtk.Action compileSaveAsAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction, null);
		this.FileMenu = new global::Gtk.Action ("FileMenu", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileMenu.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileMenu, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction1, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction, null);
		this.CompileMenu = new global::Gtk.Action ("CompileMenu", global::Mono.Unix.Catalog.GetString ("Compile"), null, null);
		this.CompileMenu.ShortLabel = global::Mono.Unix.Catalog.GetString ("Compile");
		w1.Add (this.CompileMenu, null);
		this.compileAction = new global::Gtk.Action ("compileAction", global::Mono.Unix.Catalog.GetString ("Compile"), null, null);
		this.compileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Compile");
		w1.Add (this.compileAction, "F5");
		this.compileSaveAsAction = new global::Gtk.Action ("compileSaveAsAction", global::Mono.Unix.Catalog.GetString ("Compile Save As"), null, null);
		this.compileSaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Compile Save As");
		w1.Add (this.compileSaveAsAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileMenu' action='FileMenu'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/></menu><menu name='CompileMenu' action='CompileMenu'><menuitem name='compileAction' action='compileAction'/><menuitem name='compileSaveAsAction' action='compileSaveAsAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 730;
		this.DefaultHeight = 507;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction1.Activated += new global::System.EventHandler (this.newAction_Activated);
		this.openAction.Activated += new global::System.EventHandler (this.openAction_Activated);
		this.saveAction.Activated += new global::System.EventHandler (this.saveAction_Activated);
		this.saveAsAction.Activated += new global::System.EventHandler (this.saveAsAction_Activated);
		this.compileAction.Activated += new global::System.EventHandler (this.compileAction_Activated);
		this.compileSaveAsAction.Activated += new global::System.EventHandler (this.compileSaveAsAction_Activated);
	}
}
